### ISSUE TITLE
Failed to build on Haxe 3.3

### ISSUE THREAD

**Issue by kevinresol** [jasononeil/dodrugs#1]
With the following error:

```
test/Example.hx:15: characters 9-17 : Expected class with 1 parameter but got dodrugs.Injector
test/Example.hx:15: characters 9-17 : Invalid module type
test/Example.hx:8: characters 28-36 : Void should be dodrugs.InjectorInstance
test/Example.hx:8: characters 28-36 : For function argument 'injector'
Build failed
```

**Comment by jasononeil** [comment]
Alright, finally upgraded to the 3.3 release candidate :)

The issue is that I was using `Injector` as both the place where the `create` and `extend` macros were kept, and as the 'type' for @:genericBuild.  In Haxe 3.2 this was fine, apparently it ignored the generic build when it was executing the macros.  In Haxe 3.3, this expression:

```
Injector.create( ... )
```

Triggers a generic build on `Injector` with no type parameters, and we were treating that as an error.

I have solved it by `Injector<"name">` redirecting to `InjectorInstance`, and `Injector` (with no type parameter) redirecting to`InjectorStatics`, where we run the static macros from.

The one downside of this approach is that now:

```
@inject public var inj:Injector;
```

will now try to inject `InjectorStatics`, rather than warning you that you probably need to use a type parameter.

**Comment by jasononeil** [comment]
Actually, that downside is not an issue.  The compiler rejects it with "Invalid number of type parameters for dodrugs.Injector".  Not what I was expecting, but a welcome outcome.
